name: release

on:
  push:
    branches:
      - master


jobs:

  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm test
    - run: npm run build
    - run: cp ./README.md ./release
    - run: cd ./src && npm version patch
    - run: cd ./release && npm version patch
    - run: npm config set '//registry.npmjs.org/:_authToken' "${{secrets.NPM_AUTH_TOKEN}}"
    - run: cd ./release && npm publish
      env:
        CI: true
